// Встроенный справочник самых частых товаров в магазинах РФ по штрихкодам (EAN-13).
// Позволяет мгновенно находить базовые продукты даже без интернета и без ожидания Open Food Facts.
import type { Nutriments } from '../data/types';
import type { BaseUnit, Category, Location } from '../shared/products';

export interface PresetBarcodeItem {
  name: string;
  brand: string;
  productKey: string;
  category: Category;
  qty: number;
  unit: BaseUnit;
  location: Location;
  fatPercent?: number | null;
  shelfLifeDays?: number | null;
  afterOpeningDays?: number | null;
  nutriments?: Nutriments;
  storage?: string;
}

export const POPULAR_BARCODES: Record<string, PresetBarcodeItem> = {
  // Молоко и кисломолочные
  '4607004891694': {
    name: 'Молоко 3,2%',
    brand: 'Простоквашино',
    productKey: 'milk',
    category: 'dairy',
    qty: 930,
    unit: 'ml',
    location: 'fridge',
    fatPercent: 3.2,
    shelfLifeDays: 14,
    afterOpeningDays: 3,
    nutriments: { kcal: 58, proteins: 3, fat: 3.2, carbs: 4.7 },
  },
  '4607004891687': {
    name: 'Молоко 2,5%',
    brand: 'Простоквашино',
    productKey: 'milk',
    category: 'dairy',
    qty: 930,
    unit: 'ml',
    location: 'fridge',
    fatPercent: 2.5,
    shelfLifeDays: 14,
    afterOpeningDays: 3,
    nutriments: { kcal: 52, proteins: 3, fat: 2.5, carbs: 4.7 },
  },
  '4600605021231': {
    name: 'Молоко 3,2%',
    brand: 'Домик в деревне',
    productKey: 'milk',
    category: 'dairy',
    qty: 950,
    unit: 'ml',
    location: 'fridge',
    fatPercent: 3.2,
    shelfLifeDays: 14,
    afterOpeningDays: 3,
    nutriments: { kcal: 58, proteins: 3, fat: 3.2, carbs: 4.7 },
  },
  '4600605021248': {
    name: 'Молоко 2,5%',
    brand: 'Домик в деревне',
    productKey: 'milk',
    category: 'dairy',
    qty: 950,
    unit: 'ml',
    location: 'fridge',
    fatPercent: 2.5,
    shelfLifeDays: 14,
    afterOpeningDays: 3,
    nutriments: { kcal: 52, proteins: 3, fat: 2.5, carbs: 4.7 },
  },
  '4607062568019': {
    name: 'Молоко пастеризованное 3,2%',
    brand: 'Село Зелёное',
    productKey: 'milk',
    category: 'dairy',
    qty: 950,
    unit: 'ml',
    location: 'fridge',
    fatPercent: 3.2,
    shelfLifeDays: 14,
    afterOpeningDays: 3,
    nutriments: { kcal: 59, proteins: 3, fat: 3.2, carbs: 4.7 },
  },
  '4620014020014': {
    name: 'Молоко цельное 3,2%',
    brand: 'ВкусВилл',
    productKey: 'milk',
    category: 'dairy',
    qty: 1000,
    unit: 'ml',
    location: 'fridge',
    fatPercent: 3.2,
    shelfLifeDays: 6,
    afterOpeningDays: 2,
    nutriments: { kcal: 59, proteins: 3.2, fat: 3.2, carbs: 4.7 },
  },
  '4607004891724': {
    name: 'Кефир 2,5%',
    brand: 'Простоквашино',
    productKey: 'kefir',
    category: 'dairy',
    qty: 930,
    unit: 'g',
    location: 'fridge',
    fatPercent: 2.5,
    shelfLifeDays: 14,
    afterOpeningDays: 3,
    nutriments: { kcal: 50, proteins: 3, fat: 2.5, carbs: 4 },
  },
  '4600605022016': {
    name: 'Кефир 3,2%',
    brand: 'Домик в деревне',
    productKey: 'kefir',
    category: 'dairy',
    qty: 900,
    unit: 'g',
    location: 'fridge',
    fatPercent: 3.2,
    shelfLifeDays: 14,
    afterOpeningDays: 3,
    nutriments: { kcal: 56, proteins: 3, fat: 3.2, carbs: 4 },
  },
  '4607004891762': {
    name: 'Ряженка 4%',
    brand: 'Простоквашино',
    productKey: 'ryazhenka',
    category: 'dairy',
    qty: 450,
    unit: 'g',
    location: 'fridge',
    fatPercent: 4,
    shelfLifeDays: 14,
    afterOpeningDays: 3,
    nutriments: { kcal: 64, proteins: 2.9, fat: 4, carbs: 4.1 },
  },
  '4607004891823': {
    name: 'Сметана 15%',
    brand: 'Простоквашино',
    productKey: 'sour_cream',
    category: 'dairy',
    qty: 315,
    unit: 'g',
    location: 'fridge',
    fatPercent: 15,
    shelfLifeDays: 30,
    afterOpeningDays: 3,
    nutriments: { kcal: 160, proteins: 2.7, fat: 15, carbs: 3.6 },
  },
  '4607004891830': {
    name: 'Сметана 20%',
    brand: 'Простоквашино',
    productKey: 'sour_cream',
    category: 'dairy',
    qty: 315,
    unit: 'g',
    location: 'fridge',
    fatPercent: 20,
    shelfLifeDays: 30,
    afterOpeningDays: 3,
    nutriments: { kcal: 204, proteins: 2.5, fat: 20, carbs: 3.4 },
  },
  '4810268012488': {
    name: 'Сметана 20%',
    brand: 'Брест-Литовск',
    productKey: 'sour_cream',
    category: 'dairy',
    qty: 300,
    unit: 'g',
    location: 'fridge',
    fatPercent: 20,
    shelfLifeDays: 30,
    afterOpeningDays: 3,
    nutriments: { kcal: 204, proteins: 2.5, fat: 20, carbs: 3.4 },
  },
  '4607004891908': {
    name: 'Творог 5%',
    brand: 'Простоквашино',
    productKey: 'cottage_cheese',
    category: 'dairy',
    qty: 200,
    unit: 'g',
    location: 'fridge',
    fatPercent: 5,
    shelfLifeDays: 30,
    afterOpeningDays: 3,
    nutriments: { kcal: 121, proteins: 16, fat: 5, carbs: 3 },
  },
  '4607004891915': {
    name: 'Творог 9%',
    brand: 'Простоквашино',
    productKey: 'cottage_cheese',
    category: 'dairy',
    qty: 200,
    unit: 'g',
    location: 'fridge',
    fatPercent: 9,
    shelfLifeDays: 30,
    afterOpeningDays: 3,
    nutriments: { kcal: 157, proteins: 16, fat: 9, carbs: 3 },
  },
  '4810268031236': {
    name: 'Творог мягкий 5%',
    brand: 'Савушкин',
    productKey: 'cottage_cheese',
    category: 'dairy',
    qty: 180,
    unit: 'g',
    location: 'fridge',
    fatPercent: 5,
    shelfLifeDays: 25,
    afterOpeningDays: 2,
    nutriments: { kcal: 121, proteins: 17, fat: 5, carbs: 1.8 },
  },
  '4600605023150': {
    name: 'Сливки 10%',
    brand: 'Домик в деревне',
    productKey: 'cream',
    category: 'dairy',
    qty: 200,
    unit: 'ml',
    location: 'fridge',
    fatPercent: 10,
    shelfLifeDays: 120,
    afterOpeningDays: 3,
    nutriments: { kcal: 118, proteins: 2.7, fat: 10, carbs: 4.4 },
  },
  '4600605023204': {
    name: 'Сливки 20%',
    brand: 'Домик в деревне',
    productKey: 'cream',
    category: 'dairy',
    qty: 200,
    unit: 'ml',
    location: 'fridge',
    fatPercent: 20,
    shelfLifeDays: 120,
    afterOpeningDays: 3,
    nutriments: { kcal: 206, proteins: 2.5, fat: 20, carbs: 3.9 },
  },

  // Сливочное масло и сыр
  '4810268021480': {
    name: 'Масло сливочное 82,5%',
    brand: 'Брест-Литовск',
    productKey: 'butter',
    category: 'dairy',
    qty: 180,
    unit: 'g',
    location: 'fridge',
    fatPercent: 82.5,
    shelfLifeDays: 60,
    afterOpeningDays: 14,
    nutriments: { kcal: 748, proteins: 0.6, fat: 82.5, carbs: 0.8 },
  },
  '4607026740178': {
    name: 'Масло сливочное Традиционное 82,5%',
    brand: 'Вкуснотеево',
    productKey: 'butter',
    category: 'dairy',
    qty: 200,
    unit: 'g',
    location: 'fridge',
    fatPercent: 82.5,
    shelfLifeDays: 60,
    afterOpeningDays: 14,
    nutriments: { kcal: 748, proteins: 0.6, fat: 82.5, carbs: 0.8 },
  },
  '4607014641012': {
    name: 'Масло сливочное 82,5%',
    brand: 'Экомилк',
    productKey: 'butter',
    category: 'dairy',
    qty: 180,
    unit: 'g',
    location: 'fridge',
    fatPercent: 82.5,
    shelfLifeDays: 60,
    afterOpeningDays: 14,
    nutriments: { kcal: 748, proteins: 0.6, fat: 82.5, carbs: 0.8 },
  },
  '4810268025143': {
    name: 'Сыр Классический 45%',
    brand: 'Брест-Литовск',
    productKey: 'cheese',
    category: 'dairy',
    qty: 200,
    unit: 'g',
    location: 'fridge',
    fatPercent: 45,
    shelfLifeDays: 120,
    afterOpeningDays: 7,
    nutriments: { kcal: 343, proteins: 24.6, fat: 26.5, carbs: 0 },
  },
  '4606779340017': {
    name: 'Сыр Российский',
    brand: 'ВкусВилл',
    productKey: 'cheese',
    category: 'dairy',
    qty: 200,
    unit: 'g',
    location: 'fridge',
    fatPercent: 45,
    shelfLifeDays: 90,
    afterOpeningDays: 7,
    nutriments: { kcal: 345, proteins: 24, fat: 28, carbs: 0 },
  },
  '4607008580211': {
    name: 'Сыр Ламбер 50%',
    brand: 'Ламбер',
    productKey: 'cheese',
    category: 'dairy',
    qty: 230,
    unit: 'g',
    location: 'fridge',
    fatPercent: 50,
    shelfLifeDays: 90,
    afterOpeningDays: 7,
    nutriments: { kcal: 377, proteins: 23.7, fat: 30.5, carbs: 0 },
  },
  '4002468165037': {
    name: 'Сыр творожный сливочный',
    brand: 'Hochland',
    productKey: 'cream_cheese',
    category: 'dairy',
    qty: 140,
    unit: 'g',
    location: 'fridge',
    shelfLifeDays: 120,
    afterOpeningDays: 5,
    nutriments: { kcal: 245, proteins: 6.2, fat: 23.5, carbs: 3.1 },
  },
  '4600853000019': {
    name: 'Сыр плавленый Дружба',
    brand: 'Карат',
    productKey: 'processed_cheese',
    category: 'dairy',
    qty: 90,
    unit: 'g',
    location: 'fridge',
    shelfLifeDays: 180,
    afterOpeningDays: 5,
    nutriments: { kcal: 287, proteins: 15, fat: 24.2, carbs: 2.5 },
  },

  // Яйца
  '4607028420016': {
    name: 'Яйцо куриное С0',
    brand: 'Окское',
    productKey: 'egg',
    category: 'eggs',
    qty: 10,
    unit: 'pcs',
    location: 'fridge',
    shelfLifeDays: 25,
    nutriments: { kcal: 157, proteins: 12.7, fat: 11.5, carbs: 0.7 },
  },
  '4607028420023': {
    name: 'Яйцо куриное С1',
    brand: 'Окское',
    productKey: 'egg',
    category: 'eggs',
    qty: 10,
    unit: 'pcs',
    location: 'fridge',
    shelfLifeDays: 25,
    nutriments: { kcal: 157, proteins: 12.7, fat: 11.5, carbs: 0.7 },
  },
  '4607041440015': {
    name: 'Яйцо куриное С0',
    brand: 'Волжанин',
    productKey: 'egg',
    category: 'eggs',
    qty: 10,
    unit: 'pcs',
    location: 'fridge',
    shelfLifeDays: 25,
    nutriments: { kcal: 157, proteins: 12.7, fat: 11.5, carbs: 0.7 },
  },
  '4607036980014': {
    name: 'Яйцо куриное С1',
    brand: 'Лето',
    productKey: 'egg',
    category: 'eggs',
    qty: 10,
    unit: 'pcs',
    location: 'fridge',
    shelfLifeDays: 25,
    nutriments: { kcal: 157, proteins: 12.7, fat: 11.5, carbs: 0.7 },
  },

  // Бакалея, масло, крупы, макароны
  '4600699506010': {
    name: 'Масло подсолнечное рафинированное',
    brand: 'Слобода',
    productKey: 'vegetable_oil',
    category: 'other',
    qty: 1000,
    unit: 'ml',
    location: 'pantry',
    fatPercent: 99.9,
    shelfLifeDays: 365,
    afterOpeningDays: 90,
    nutriments: { kcal: 899, proteins: 0, fat: 99.9, carbs: 0 },
  },
  '4600699501015': {
    name: 'Масло подсолнечное Классическое',
    brand: 'Олейна',
    productKey: 'vegetable_oil',
    category: 'other',
    qty: 1000,
    unit: 'ml',
    location: 'pantry',
    fatPercent: 99.9,
    shelfLifeDays: 365,
    afterOpeningDays: 90,
    nutriments: { kcal: 899, proteins: 0, fat: 99.9, carbs: 0 },
  },
  '4600862002127': {
    name: 'Гречка в пакетиках',
    brand: 'Увелка',
    productKey: 'buckwheat',
    category: 'grains',
    qty: 400,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 540,
    afterOpeningDays: 365,
    nutriments: { kcal: 330, proteins: 12, fat: 2, carbs: 62 },
  },
  '4601136001013': {
    name: 'Крупа гречневая ядрица',
    brand: 'Мистраль',
    productKey: 'buckwheat',
    category: 'grains',
    qty: 900,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 540,
    afterOpeningDays: 365,
    nutriments: { kcal: 330, proteins: 12.6, fat: 2.6, carbs: 64 },
  },
  '4601136002010': {
    name: 'Рис Кубань круглозерный',
    brand: 'Мистраль',
    productKey: 'rice',
    category: 'grains',
    qty: 900,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 540,
    afterOpeningDays: 365,
    nutriments: { kcal: 340, proteins: 7, fat: 1, carbs: 74 },
  },
  '4600862001014': {
    name: 'Хлопья овсяные Геркулес Традиционный',
    brand: 'Русский продукт',
    productKey: 'oats',
    category: 'grains',
    qty: 500,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 365,
    afterOpeningDays: 180,
    nutriments: { kcal: 352, proteins: 12.3, fat: 6.2, carbs: 61.8 },
  },
  '4601674000011': {
    name: 'Мука пшеничная в/с',
    brand: 'Макфа',
    productKey: 'flour',
    category: 'grains',
    qty: 1000,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 365,
    afterOpeningDays: 180,
    nutriments: { kcal: 334, proteins: 10.3, fat: 1.1, carbs: 70.6 },
  },
  '4601674000028': {
    name: 'Мука пшеничная в/с 2 кг',
    brand: 'Макфа',
    productKey: 'flour',
    category: 'grains',
    qty: 2000,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 365,
    afterOpeningDays: 180,
    nutriments: { kcal: 334, proteins: 10.3, fat: 1.1, carbs: 70.6 },
  },
  '8076809513753': {
    name: 'Спагетти №5',
    brand: 'Barilla',
    productKey: 'pasta',
    category: 'grains',
    qty: 500,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 730,
    afterOpeningDays: 365,
    nutriments: { kcal: 359, proteins: 12.5, fat: 2, carbs: 71.2 },
  },
  '8076809513739': {
    name: 'Пенне Ригате №73',
    brand: 'Barilla',
    productKey: 'pasta',
    category: 'grains',
    qty: 500,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 730,
    afterOpeningDays: 365,
    nutriments: { kcal: 359, proteins: 12.5, fat: 2, carbs: 71.2 },
  },
  '4601674010010': {
    name: 'Спагетти',
    brand: 'Макфа',
    productKey: 'pasta',
    category: 'grains',
    qty: 500,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 730,
    afterOpeningDays: 365,
    nutriments: { kcal: 356, proteins: 12, fat: 1.3, carbs: 70.5 },
  },
  '4601674010027': {
    name: 'Макароны Перья',
    brand: 'Макфа',
    productKey: 'pasta',
    category: 'grains',
    qty: 400,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 730,
    afterOpeningDays: 365,
    nutriments: { kcal: 356, proteins: 12, fat: 1.3, carbs: 70.5 },
  },
  '4601955000013': {
    name: 'Сахар-песок',
    brand: 'Русский сахар',
    productKey: 'sugar',
    category: 'sweets',
    qty: 1000,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 1460,
    afterOpeningDays: 730,
    nutriments: { kcal: 398, proteins: 0, fat: 0, carbs: 99.7 },
  },

  // Соусы и консервы
  '4600699503019': {
    name: 'Майонез Провансаль 67%',
    brand: 'Слобода',
    productKey: 'mayonnaise',
    category: 'sauces',
    qty: 400,
    unit: 'ml',
    location: 'fridge',
    fatPercent: 67,
    shelfLifeDays: 90,
    afterOpeningDays: 14,
    nutriments: { kcal: 613, proteins: 0.5, fat: 67, carbs: 2.1 },
  },
  '8715700421384': {
    name: 'Кетчуп томатный',
    brand: 'Heinz',
    productKey: 'ketchup',
    category: 'sauces',
    qty: 350,
    unit: 'g',
    location: 'fridge',
    shelfLifeDays: 365,
    afterOpeningDays: 30,
    nutriments: { kcal: 104, proteins: 1.2, fat: 0.1, carbs: 24.1 },
  },
  '3083680085304': {
    name: 'Горошек зеленый Нежный',
    brand: 'Bonduelle',
    productKey: 'peas_canned',
    category: 'canned',
    qty: 400,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 1460,
    afterOpeningDays: 2,
    nutriments: { kcal: 73, proteins: 5.5, fat: 0.7, carbs: 7.4 },
  },
  '3083680085311': {
    name: 'Кукуруза сладкая',
    brand: 'Bonduelle',
    productKey: 'corn_canned',
    category: 'canned',
    qty: 340,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 1460,
    afterOpeningDays: 2,
    nutriments: { kcal: 80, proteins: 2.9, fat: 1.2, carbs: 12.8 },
  },
  '4607011580147': {
    name: 'Томатная паста',
    brand: 'Помидорка',
    productKey: 'tomato_paste',
    category: 'sauces',
    qty: 250,
    unit: 'g',
    location: 'pantry',
    shelfLifeDays: 1095,
    afterOpeningDays: 7,
    nutriments: { kcal: 79, proteins: 4.8, fat: 0, carbs: 15 },
  },

  // Мясные изделия
  '4607065521011': {
    name: 'Сосиски Молочные',
    brand: 'Вязанка',
    productKey: 'sausages',
    category: 'meat',
    qty: 450,
    unit: 'g',
    location: 'fridge',
    shelfLifeDays: 30,
    afterOpeningDays: 3,
    nutriments: { kcal: 236, proteins: 11, fat: 20, carbs: 3 },
  },
  '4607005401014': {
    name: 'Сосиски Докторские',
    brand: 'Клинский',
    productKey: 'sausages',
    category: 'meat',
    qty: 460,
    unit: 'g',
    location: 'fridge',
    shelfLifeDays: 30,
    afterOpeningDays: 3,
    nutriments: { kcal: 245, proteins: 12, fat: 21, carbs: 2 },
  },
  '4607144460019': {
    name: 'Фарш Домашний',
    brand: 'Мираторг',
    productKey: 'minced_meat',
    category: 'meat',
    qty: 400,
    unit: 'g',
    location: 'fridge',
    shelfLifeDays: 12,
    afterOpeningDays: 1,
    nutriments: { kcal: 290, proteins: 14, fat: 26, carbs: 0 },
  },
  '4607062430019': {
    name: 'Филе грудки цыпленка',
    brand: 'Петелинка',
    productKey: 'chicken_breast',
    category: 'poultry',
    qty: 850,
    unit: 'g',
    location: 'fridge',
    shelfLifeDays: 8,
    afterOpeningDays: 1,
    nutriments: { kcal: 113, proteins: 23.6, fat: 1.9, carbs: 0.4 },
  },
};

/** Найти товар во встроенном офлайн-справочнике штрихкодов */
export function findPresetBarcode(code: string): PresetBarcodeItem | null {
  return POPULAR_BARCODES[code] ?? null;
}
